// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
<<<<<<< HEAD
    id: '26d6d535-5164-443d-82f6-4c695caf7688',
    name: 'BDHadoopHumboldtCRPAdhocTestShortTerm',
=======
    id: '12f44720-8952-422c-bb7d-28831c2de639',
    name: 'BDHadoopHumboltCRUDReliability',
>>>>>>> 020e4c6585e0b3fd70209f353d3dc71a397246bc
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_ARM_TEST_LOCATION'] = 'NorthCentralUS';
  process.env['SSHCERT'] = 'test/myCert.pem';
};

exports.scopes = [];

<<<<<<< HEAD
 exports.randomTestIdsGenerated = function() { return ['xplatTestRgHDInsightClusterCreate912','xplatTestHDInsightClusterCreate5946','xplatTestHDInsightClusterCreate2943','xplatTestHDInsightClusterCreate6003'];};
=======
 exports.randomTestIdsGenerated = function() { return ['xplatTestRgHDInsightClusterCreate1069','xplatTestHDInsightClusterCreate3257','xplatTestHDInsightClusterCreate2050','xplatTestHDInsightClusterCreate3731'];};
>>>>>>> 020e4c6585e0b3fd70209f353d3dc71a397246bc
